server:
  port: 9091

spring:
  data:
    mongodb:
      database: xy-inc
      uri: mongodb://admin:admin123@ds261626.mlab.com:61626/xy-inc
      
eureka:
  instance:
    hostname: localhost
    port: 9090
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  service:
    wait-time-in-ms-when-sync-empty: 3000